const passages={
 beginner:["Typing practice builds accuracy before speed becomes natural. Keep your hands relaxed and focus on each character.","A good typing habit starts with steady rhythm, correct finger placement, and patient repetition. Speed follows consistency."],
 intermediate:["Strong typists do not chase every keystroke. They build a steady rhythm, read ahead, and let accurate movement become automatic.","Consistent practice improves typing speed, confidence, and control. The goal is not simply to type quickly, but to type correctly under pressure."],
 advanced:["Modern digital work rewards people who can communicate ideas quickly and accurately. Efficient typing gives you more time to think, edit, research, and create.","Precision matters when you work with code, analytics, marketing reports, documentation, and long-form writing. A fast typist still needs reliable accuracy."],
 expert:["Great typing performance is a balance between speed, accuracy, rhythm, and concentration. The fastest result is not useful when careless errors make the final message harder to understand.","Technology changes quickly, but clear communication remains valuable. Practise difficult punctuation, numbers, capitalization, and longer sentences until your hands respond without hesitation."]
};
const rows=[
[{k:'`',code:'Backquote'},{k:'1',code:'Digit1'},{k:'2',code:'Digit2'},{k:'3',code:'Digit3'},{k:'4',code:'Digit4'},{k:'5',code:'Digit5'},{k:'6',code:'Digit6'},{k:'7',code:'Digit7'},{k:'8',code:'Digit8'},{k:'9',code:'Digit9'},{k:'0',code:'Digit0'},{k:'-',code:'Minus'},{k:'=',code:'Equal'},{k:'BACK',code:'Backspace'}],
[{k:'TAB',code:'Tab'},{k:'Q',code:'KeyQ'},{k:'W',code:'KeyW'},{k:'E',code:'KeyE'},{k:'R',code:'KeyR'},{k:'T',code:'KeyT'},{k:'Y',code:'KeyY'},{k:'U',code:'KeyU'},{k:'I',code:'KeyI'},{k:'O',code:'KeyO'},{k:'P',code:'KeyP'},{k:'[',code:'BracketLeft'},{k:']',code:'BracketRight'},{k:'\\',code:'Backslash'}],
[{k:'CAPS',code:'CapsLock'},{k:'A',code:'KeyA'},{k:'S',code:'KeyS'},{k:'D',code:'KeyD'},{k:'F',code:'KeyF'},{k:'G',code:'KeyG'},{k:'H',code:'KeyH'},{k:'J',code:'KeyJ'},{k:'K',code:'KeyK'},{k:'L',code:'KeyL'},{k:';',code:'Semicolon'},{k:"'",code:'Quote'},{k:'ENTER',code:'Enter'}],
[{k:'SHIFT',code:'ShiftLeft'},{k:'Z',code:'KeyZ'},{k:'X',code:'KeyX'},{k:'C',code:'KeyC'},{k:'V',code:'KeyV'},{k:'B',code:'KeyB'},{k:'N',code:'KeyN'},{k:'M',code:'KeyM'},{k:',',code:'Comma'},{k:'.',code:'Period'},{k:'/',code:'Slash'},{k:'SHIFT',code:'ShiftRight'}],
[{k:'CTRL',code:'ControlLeft'},{k:'ALT',code:'AltLeft'},{k:'SPACE',code:'Space'},{k:'ALT',code:'AltRight'},{k:'CTRL',code:'ControlRight'}]
];
const $=id=>document.getElementById(id);const els={landing:$('landing'),userName:$('userName'),app:$('app'),text:$('text'),input:$('input'),level:$('level'),mode:$('mode'),wpm:$('wpm'),net:$('net'),accuracy:$('accuracy'),errors:$('errors'),timer:$('timer'),status:$('status'),keyboard:$('keyboard'),history:$('history'),bestWpm:$('bestWpm'),bestAccuracy:$('bestAccuracy'),testsDone:$('testsDone'),certModal:$('certificateModal')};
let state={text:'',typed:'',errors:0,start:0,elapsed:0,running:false,finished:false,interval:null,sound:true,feedback:new Map()};const KEY='sagarTypingRecordsV3';
function records(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}function save(r){localStorage.setItem(KEY,JSON.stringify(r))}function escape(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}function pick(){let p=passages[els.level.value]||passages.beginner;return p[Math.floor(Math.random()*p.length)]}
function buildKeyboard(){els.keyboard.innerHTML=rows.map(r=>`<div class="key-row">${r.map(x=>`<div class="key ${x.k==='SPACE'?'space':''} ${x.k==='SHIFT'?'shift':''} ${x.k==='ENTER'?'enter':''}" data-code="${x.code}">${escape(x.k)}</div>`).join('')}</div>`).join('')}
function codeFor(ch){const map={' ':'Space','`':'Backquote','1':'Digit1','2':'Digit2','3':'Digit3','4':'Digit4','5':'Digit5','6':'Digit6','7':'Digit7','8':'Digit8','9':'Digit9','0':'Digit0','-':'Minus','=':'Equal','[':'BracketLeft',']':'BracketRight','\\':'Backslash',';':'Semicolon',"'":'Quote',',':'Comma','.':'Period','/':'Slash'};return map[ch]||(ch.match(/[a-z]/i)?`Key${ch.toUpperCase()}`:null)}
function expectedKey(){els.keyboard.querySelectorAll('.key').forEach(k=>k.classList.remove('next'));const ch=state.text[state.typed.length];if(!ch)return;const key=els.keyboard.querySelector(`[data-code="${codeFor(ch)}"]`);if(key)key.classList.add('next');if(/[A-Z]/.test(ch))els.keyboard.querySelectorAll('[data-code^="Shift"]').forEach(k=>k.classList.add('next'))}
function renderText(){els.text.innerHTML=[...state.text].map((c,i)=>`<span class="typing-char ${i===state.typed.length?'current':''} ${i<state.typed.length?(state.typed[i]===c?'correct':'wrong'):''}">${escape(c)}</span>`).join('');expectedKey()}
function metrics(){const mins=Math.max(state.elapsed/60,1/6000),chars=state.typed.length;let correct=0;for(let i=0;i<chars;i++)if(state.typed[i]===state.text[i])correct++;const raw=(chars/5)/mins,acc=chars?correct/chars*100:100,net=Math.max(0,raw-(state.errors/5/mins));return{raw,acc,net,correct}}
function update(){const m=metrics();els.wpm.textContent=Math.round(m.raw);els.net.textContent=Math.round(m.net);els.accuracy.textContent=`${m.acc.toFixed(1)}%`;els.errors.textContent=state.errors;els.timer.textContent=fmt(state.elapsed)}
function begin(){if(state.running)return;state.running=true;state.finished=false;state.start=performance.now()-state.elapsed*1000;els.status.textContent='TYPING';els.input.disabled=false;els.input.focus();clearInterval(state.interval);state.interval=setInterval(()=>{state.elapsed=(performance.now()-state.start)/1000;update();const limit=els.mode.value;if(limit!=='passage'&&state.elapsed>=+limit)finish('Time complete')},100)}
function newTest(){clearInterval(state.interval);state={text:pick(),typed:'',errors:0,start:0,elapsed:0,running:false,finished:false,interval:null,sound:state.sound,feedback:new Map()};renderText();update();els.input.value='';els.input.disabled=true;els.status.textContent='READY';}
function startOver(){newTest();els.input.disabled=false;begin()}
function handleKey(e){if(e.key==='Escape'){e.preventDefault();newTest();return}if(['Tab','Alt','Control','Meta','CapsLock'].includes(e.key))return;if(!state.running&&!state.finished)begin();if(state.finished)return;if(e.key==='Backspace'){e.preventDefault();state.typed=state.typed.slice(0,-1);renderText();update();return}if(e.key.length!==1)return;e.preventDefault();if(state.typed.length>=state.text.length)return;state.typed+=e.key;const i=state.typed.length-1;const ok=e.key===state.text[i];if(!ok)state.errors++;feedback(e.code,ok);renderText();update();if(state.typed.length>=state.text.length)finish('Passage complete')}
function feedback(code,ok){const k=els.keyboard.querySelector(`[data-code="${code}"]`);if(!k)return;k.classList.remove('next');k.classList.add(ok?'correct':'wrong');if(state.sound)tone(ok?'ok':'bad');setTimeout(expectedKey,20)}
function tone(kind){try{const C=tone.c||(tone.c=new AudioContext()),o=C.createOscillator(),g=C.createGain();o.frequency.value=kind==='bad'?170:430;g.gain.value=.018;o.connect(g);g.connect(C.destination);o.start();o.stop(C.currentTime+.04)}catch{}}
function finish(reason='Finished'){if(state.finished)return;if(!state.running&&reason!=='Finished manually')return;state.elapsed=els.mode.value==='passage'?state.elapsed:Math.min(state.elapsed,+els.mode.value);state.running=false;state.finished=true;clearInterval(state.interval);update();const m=metrics();const row={date:new Date().toISOString(),wpm:Math.round(m.raw),net:Math.round(m.net),accuracy:+m.acc.toFixed(1),errors:state.errors,mode:els.mode.value==='passage'?'Passage':els.mode.value+' sec'};save([row,...records()].slice(0,50));els.status.textContent=reason.toUpperCase();els.input.disabled=true;renderHistory();profile();if(m.acc>98)showCertificate(m)}
function renderHistory(){const r=records();els.history.innerHTML=r.slice(0,12).map(x=>`<tr><td>${new Date(x.date).toLocaleDateString()}</td><td>${x.wpm}</td><td>${x.accuracy}%</td><td>${escape(x.mode)}</td></tr>`).join('')||'<tr><td colspan="4">No tests completed yet.</td></tr>'}function profile(){const r=records();els.bestWpm.textContent=Math.max(0,...r.map(x=>x.wpm));els.bestAccuracy.textContent=`${Math.max(0,...r.map(x=>x.accuracy)).toFixed(1)}%`;els.testsDone.textContent=r.length}
function showCertificate(m){$('certName').textContent=(els.userName.value.trim()||'Typing Test User');$('certWpm').textContent=Math.round(m.net);$('certAcc').textContent=`${m.acc.toFixed(1)}%`;$('certErrors').textContent=state.errors;$('certDate').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});els.certModal.classList.remove('hidden')}
function openApp(){els.landing.classList.add('hidden');els.app.classList.remove('hidden');location.hash='app';newTest();renderHistory();profile();window.scrollTo({top:0,behavior:'smooth'})}function home(){els.app.classList.add('hidden');els.landing.classList.remove('hidden');history.replaceState(null,'','#landing');window.scrollTo({top:0,behavior:'smooth'})}
function route(){if(location.hash==='#app')openApp();else{els.app.classList.add('hidden');els.landing.classList.remove('hidden')}}
document.querySelectorAll('[data-start-app]').forEach(b=>b.addEventListener('click',openApp));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',home));$('restart').addEventListener('click',startOver);$('finish').addEventListener('click',()=>state.running&&finish('Finished manually'));$('input').addEventListener('keydown',handleKey);$('text').addEventListener('click',()=>els.input.focus());$('clear').addEventListener('click',()=>{localStorage.removeItem(KEY);renderHistory();profile()});$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇'});$('themeBtn').addEventListener('click',()=>document.body.classList.toggle('light'));$('closeCert').addEventListener('click',()=>els.certModal.classList.add('hidden'));$('closeCert2').addEventListener('click',()=>els.certModal.classList.add('hidden'));$('printCert').addEventListener('click',()=>window.print());$('level').addEventListener('change',newTest);$('mode').addEventListener('change',newTest);window.addEventListener('hashchange',route);document.querySelector('[data-year]').textContent=new Date().getFullYear();buildKeyboard();newTest();renderHistory();profile();route();
