const passages={
beginner:["The quick brown fox jumps over the lazy dog. Practice every day and your fingers will learn the rhythm of typing.","Typing becomes easier when you keep a steady pace, watch the text carefully, and focus on accuracy before speed."],
intermediate:["Good typing is a balance between speed and accuracy. A consistent rhythm helps you write emails, reports, notes, and messages with less effort.","When you practise regularly, your hands begin to remember common words and patterns. Keep your eyes on the text and let your fingers follow naturally."],
advanced:["Digital work rewards people who can communicate clearly and quickly. Accurate typing saves time when editing documents, writing code, analysing data, and preparing marketing campaigns.","A strong typing rhythm should survive punctuation, capital letters, numbers, and longer sentences. Slow down when necessary, then build speed without sacrificing precision."],
expert:["Technology changes quickly, but clear communication remains valuable. Practise difficult punctuation, numbers, capitalization, and technical vocabulary until your hands respond without hesitation.","Precision matters when you work with code, analytics, marketing reports, documentation, and long-form writing. A fast typist still needs reliable accuracy to produce useful work."]};
const keyDrills=["asdf jkl; asdf jkl; fjfj dkdk slsl aaaa jjjj","qwer uiop qwer uiop asdf jkl; zxcv nm,.","12345 67890 qwert yuiop asdfg hjkl; zxcvb nm,./"];
const rows=[
[{k:'`',code:'Backquote'},{k:'1',code:'Digit1'},{k:'2',code:'Digit2'},{k:'3',code:'Digit3'},{k:'4',code:'Digit4'},{k:'5',code:'Digit5'},{k:'6',code:'Digit6'},{k:'7',code:'Digit7'},{k:'8',code:'Digit8'},{k:'9',code:'Digit9'},{k:'0',code:'Digit0'},{k:'-',code:'Minus'},{k:'=',code:'Equal'},{k:'BACK',code:'Backspace'}],
[{k:'TAB',code:'Tab'},{k:'Q',code:'KeyQ'},{k:'W',code:'KeyW'},{k:'E',code:'KeyE'},{k:'R',code:'KeyR'},{k:'T',code:'KeyT'},{k:'Y',code:'KeyY'},{k:'U',code:'KeyU'},{k:'I',code:'KeyI'},{k:'O',code:'KeyO'},{k:'P',code:'KeyP'},{k:'[',code:'BracketLeft'},{k:']',code:'BracketRight'},{k:'\\',code:'Backslash'}],
[{k:'CAPS',code:'CapsLock'},{k:'A',code:'KeyA'},{k:'S',code:'KeyS'},{k:'D',code:'KeyD'},{k:'F',code:'KeyF'},{k:'G',code:'KeyG'},{k:'H',code:'KeyH'},{k:'J',code:'KeyJ'},{k:'K',code:'KeyK'},{k:'L',code:'KeyL'},{k:';',code:'Semicolon'},{k:"'",code:'Quote'},{k:'ENTER',code:'Enter'}],
[{k:'SHIFT',code:'ShiftLeft'},{k:'Z',code:'KeyZ'},{k:'X',code:'KeyX'},{k:'C',code:'KeyC'},{k:'V',code:'KeyV'},{k:'B',code:'KeyB'},{k:'N',code:'KeyN'},{k:'M',code:'KeyM'},{k:',',code:'Comma'},{k:'.',code:'Period'},{k:'/',code:'Slash'},{k:'SHIFT',code:'ShiftRight'}],
[{k:'CTRL',code:'ControlLeft'},{k:'ALT',code:'AltLeft'},{k:'SPACE',code:'Space'},{k:'ALT',code:'AltRight'},{k:'CTRL',code:'ControlRight'}]];
const $=id=>document.getElementById(id);const els={app:$('app'),text:$('text'),input:$('input'),level:$('level'),mode:$('mode'),userName:$('userName'),wpm:$('wpm'),net:$('net'),accuracy:$('accuracy'),errors:$('errors'),timer:$('timer'),status:$('status'),keyboard:$('keyboard'),history:$('history'),bestWpm:$('bestWpm'),bestAccuracy:$('bestAccuracy'),testsDone:$('testsDone'),certModal:$('certificateModal')};
const KEY='sagarTypingRecordsV4';let selectedMode='60';
let state={text:'',typed:'',errors:0,start:0,elapsed:0,running:false,finished:false,interval:null,sound:true};
function records(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}}function save(r){localStorage.setItem(KEY,JSON.stringify(r))}function escape(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}function pick(){const p=passages[els.level.value]||passages.beginner;return p[Math.floor(Math.random()*p.length)]}
function modeInfo(){const m=selectedMode;if(m==='passage')return{limit:null,label:'Passage'};if(m.startsWith('page'))return{limit:null,label:m==='page1'?'1 Page':m==='page2'?'2 Pages':'3 Pages'};if(m.startsWith('keys'))return{limit:Number(m.slice(4))*60,label:`${m.slice(4)}:00 Key Test`};return{limit:Number(m),label:`${Math.round(Number(m)/60)} Minute`}}
function makePassage(){const m=selectedMode;if(m.startsWith('page')){const n=Number(m.slice(4));const p=passages[els.level.value];return Array.from({length:n},(_,i)=>p[i%p.length]).join(' ')}if(m.startsWith('keys'))return keyDrills[Math.floor(Math.random()*keyDrills.length)];return pick()}
function buildKeyboard(){els.keyboard.innerHTML=rows.map(r=>`<div class="key-row">${r.map(x=>`<div class="key ${x.k==='SPACE'?'space':''} ${x.k==='SHIFT'?'shift':''} ${x.k==='ENTER'?'enter':''}" data-code="${x.code}">${escape(x.k)}</div>`).join('')}</div>`).join('')}
function codeFor(ch){const map={' ':'Space','`':'Backquote','1':'Digit1','2':'Digit2','3':'Digit3','4':'Digit4','5':'Digit5','6':'Digit6','7':'Digit7','8':'Digit8','9':'Digit9','0':'Digit0','-':'Minus','=':'Equal','[':'BracketLeft',']':'BracketRight','\\':'Backslash',';':'Semicolon',"'":'Quote',',':'Comma','.':'Period','/':'Slash'};return map[ch]||(ch.match(/[a-z]/i)?`Key${ch.toUpperCase()}`:null)}
function resetKeyColors(){els.keyboard.querySelectorAll('.key').forEach(k=>k.classList.remove('correct','wrong','next'))}
function expectedKey(){els.keyboard.querySelectorAll('.key').forEach(k=>k.classList.remove('next'));const ch=state.text[state.typed.length];if(!ch)return;const key=els.keyboard.querySelector(`[data-code="${codeFor(ch)}"]`);if(key)key.classList.add('next');if(/[A-Z]/.test(ch)){const s=els.keyboard.querySelector('[data-code="ShiftLeft"]');if(s)s.classList.add('next')}}
function renderText(){els.text.innerHTML=[...state.text].map((c,i)=>`<span class="typing-char ${i===state.typed.length?'current':''} ${i<state.typed.length?(state.typed[i]===c?'correct':'wrong'):''}">${escape(c)}</span>`).join('');expectedKey()}
function metrics(){const mins=Math.max(state.elapsed/60,1/6000),chars=state.typed.length;let correct=0;for(let i=0;i<chars;i++)if(state.typed[i]===state.text[i])correct++;const raw=(chars/5)/mins,acc=chars?correct/chars*100:100,net=Math.max(0,raw-(state.errors/5/mins));return{raw,acc,net,correct}}
function update(){const m=metrics();els.wpm.textContent=Math.round(m.raw);els.net.textContent=Math.round(m.net);els.accuracy.textContent=`${m.acc.toFixed(1)}%`;els.errors.textContent=state.errors;els.timer.textContent=fmt(state.elapsed)}
function newTest(){clearInterval(state.interval);state={text:makePassage(),typed:'',errors:0,start:0,elapsed:0,running:false,finished:false,interval:null,sound:state.sound};resetKeyColors();renderText();update();els.input.value='';els.input.disabled=true;els.status.textContent='READY'}
function startTest(mode=null,level=null){if(mode)selectedMode=mode;if(level)els.level.value=level;const allowed=['60','180','300','passage'];if(['page1','page2','page3','keys1','keys3','keys5'].includes(selectedMode)){els.mode.value=selectedMode.startsWith('page')?'passage':'60'}else if(allowed.includes(selectedMode))els.mode.value=selectedMode;newTest();els.app.classList.remove('hidden');document.querySelectorAll('body>main,.topbar,.site-footer').forEach(x=>x.classList.add('hidden'));location.hash='app';window.scrollTo({top:0});els.input.disabled=false;els.input.focus()}
function begin(){if(state.running)return;state.running=true;state.finished=false;state.start=performance.now()-state.elapsed*1000;els.status.textContent='TYPING';clearInterval(state.interval);state.interval=setInterval(()=>{state.elapsed=(performance.now()-state.start)/1000;update();const limit=modeInfo().limit;if(limit&&state.elapsed>=limit)finish('Time complete')},100)}
function handleKey(e){if(e.key==='Escape'){e.preventDefault();newTest();return}if(['Tab','Alt','Control','Meta','CapsLock'].includes(e.key))return;if(!state.running&&!state.finished)begin();if(state.finished)return;if(e.key==='Backspace'){e.preventDefault();state.typed=state.typed.slice(0,-1);renderText();update();return}if(e.key.length!==1)return;e.preventDefault();if(state.typed.length>=state.text.length)return;state.typed+=e.key;const i=state.typed.length-1;const ok=e.key===state.text[i];if(!ok)state.errors++;feedback(e.code,ok);renderText();update();if(state.typed.length>=state.text.length)finish('Passage complete')}
function feedback(code,ok){const k=els.keyboard.querySelector(`[data-code="${code}"]`);if(!k)return;k.classList.remove('next');k.classList.add(ok?'correct':'wrong');if(state.sound)tone(ok?'ok':'bad');setTimeout(expectedKey,20)}
function tone(kind){try{const C=tone.c||(tone.c=new AudioContext()),o=C.createOscillator(),g=C.createGain();o.frequency.value=kind==='bad'?170:430;g.gain.value=.018;o.connect(g);g.connect(C.destination);o.start();o.stop(C.currentTime+.04)}catch{}}
function finish(reason='Finished'){if(state.finished||(!state.running&&reason!=='Finished manually'))return;state.running=false;state.finished=true;clearInterval(state.interval);update();const m=metrics();const info=modeInfo();const row={date:new Date().toISOString(),wpm:Math.round(m.raw),net:Math.round(m.net),accuracy:+m.acc.toFixed(1),errors:state.errors,mode:info.label};save([row,...records()].slice(0,50));els.status.textContent=reason.toUpperCase();els.input.disabled=true;renderHistory();profile();if(m.acc>98)showCertificate(m)}
function renderHistory(){const r=records();els.history.innerHTML=r.slice(0,12).map(x=>`<tr><td>${new Date(x.date).toLocaleDateString()}</td><td>${x.wpm}</td><td>${x.accuracy}%</td><td>${escape(x.mode)}</td></tr>`).join('')||'<tr><td colspan="4">No tests completed yet.</td></tr>'}
function profile(){const r=records();els.bestWpm.textContent=Math.max(0,...r.map(x=>x.wpm));els.bestAccuracy.textContent=`${Math.max(0,...r.map(x=>x.accuracy)).toFixed(1)}%`;els.testsDone.textContent=r.length}
function showCertificate(m){const name=els.userName.value.trim()||'Typing Test User';$('certName').textContent=name;$('certWpm').textContent=Math.round(m.net);$('certAcc').textContent=`${m.acc.toFixed(1)}%`;$('certErrors').textContent=state.errors;$('certDate').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});$('certId').textContent=`STT-${new Date().getFullYear()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;els.certModal.classList.remove('hidden')}
function showHome(){els.app.classList.add('hidden');document.querySelectorAll('body>main,.topbar,.site-footer').forEach(x=>x.classList.remove('hidden'));history.replaceState(null,'','#home');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-start-app]').forEach(b=>b.addEventListener('click',e=>startTest(b.dataset.testMode||null,b.dataset.testLevel||null)));document.querySelectorAll('[data-test-mode]').forEach(b=>b.addEventListener('click',()=>startTest(b.dataset.testMode)));document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',showHome));$('restart').addEventListener('click',newTest);$('finish').addEventListener('click',()=>state.running&&finish('Finished manually'));$('input').addEventListener('keydown',handleKey);$('text').addEventListener('click',()=>els.input.focus());$('clear').addEventListener('click',()=>{localStorage.removeItem(KEY);renderHistory();profile()});$('soundBtn').addEventListener('click',()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇'});$('themeBtn').addEventListener('click',()=>document.body.classList.toggle('theme-dark'));$('closeCert').addEventListener('click',()=>els.certModal.classList.add('hidden'));$('closeCert2').addEventListener('click',()=>els.certModal.classList.add('hidden'));$('printCert').addEventListener('click',()=>window.print());$('level').addEventListener('change',newTest);$('mode').addEventListener('change',()=>{selectedMode=els.mode.value;newTest()});document.querySelector('[data-year]').textContent=new Date().getFullYear();buildKeyboard();newTest();renderHistory();profile();
